plugins {
	id 'dev.architectury.loom' version "${architectury_loom_version}" apply false
	id 'architectury-plugin' version "${architectury_plugin_version}"
	id 'com.gradleup.shadow' version "${shadow_version}" apply false
}

architectury {
	minecraft = project.minecraft_version
}

allprojects {
	group = rootProject.maven_group
	version = rootProject.mod_version
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'
	apply plugin: 'java'

	base {
		archivesName = "$rootProject.archives_name-$rootProject.minecraft_version-$project.name"
	}

	repositories{

	}

	dependencies{
		minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
		mappings "net.fabricmc:yarn:$rootProject.yarn_mappings:v2"
	}

	java {
		withSourcesJar()

		sourceCompatibility = JavaVersion.VERSION_1_8
		targetCompatibility = JavaVersion.VERSION_1_8

		toolchain.languageVersion=JavaLanguageVersion.of(8)
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 8

		options.compilerArgs.removeIf { it == "--release" }
		if (options.hasProperty("release")) {
			options.release.set(null)
		}
	}

	tasks.withType(JavaExec).configureEach {
		def toolchainService = project.extensions.getByType(JavaToolchainService)
		def launcher = toolchainService.launcherFor{languageVersion = JavaLanguageVersion.of(8)}.get()

		executable = launcher.executablePath.asFile.absolutePath
	}
}