# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod_name = Plague's Chat Timestamps
mod_description = This mod adds customizable timestamps to chat!
mod_author = Plague1337
mod_sources = https://github.com/PlagueTR/ChatTimestamps
mod_license = MIT
mod_java = 21

maven_group = space.plague
archives_name = plagueschattimestamps
enabled_platforms = fabric,forge,neoforge

mod_version = 1.2.1

# Minecraft properties
minecraft_version = 1.21.1

# Common
architectury_api_version = 13.0.8
architectury_plugin_version = 3.4-SNAPSHOT
architectury_loom_version = 1.11-SNAPSHOT

shadow_version = 8.3.6

common_cloth_config_version = 15.0.140

# Fabric
fabric_loader_version = 0.17.2
fabric_api_version = 0.116.12+1.21.1

fabric_mod_menu_version = 11.0.4

# Forge
forge_version = 1.21.1-52.1.0
forge_loader_version = [52,)

# NeoForge
neoforge_version = 21.1.233
neoforge_loader_version = [1,)