# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod_name = Plague's Chat Timestamps
mod_description = This mod adds customizable timestamps to chat!
mod_author = Plague1337
mod_sources = https://github.com/PlagueTR/ChatTimestamps
mod_license = MIT
mod_java = 16

maven_group = space.plague
archives_name = plagueschattimestamps
enabled_platforms = fabric,forge

mod_version = 1.2.0

# Minecraft properties
minecraft_version = 1.17.1
yarn_mappings = 1.17.1+build.1

# Common
architectury_api_version = 2.10.12
architectury_plugin_version = 3.4-SNAPSHOT
architectury_loom_version = 1.11-SNAPSHOT

shadow_version = 8.3.6

common_cloth_config_version = 5.3.63

# Fabric
fabric_loader_version = 0.19.3
fabric_api_version = 0.46.1+1.17

fabric_mod_menu_version = 2.0.17

# Forge
forge_version = 1.17.1-37.1.1
forge_loader_version = [37,)