# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod_name = Plague's Chat Timestamps
mod_description = This mod adds customizable timestamps to chat!
mod_author = Plague1337
mod_sources = https://github.com/PlagueTR/ChatTimestamps
mod_license = MIT
mod_java = 21

maven_group = space.plague
archives_name = plagueschattimestamps
enabled_platforms = fabric,neoforge

mod_version = 1.2.1

# Minecraft properties
minecraft_version = 1.21.6

# Common
architectury_api_version = 17.0.6
architectury_plugin_version = 3.4-SNAPSHOT
architectury_loom_version = 1.11-SNAPSHOT

shadow_version = 8.3.6

common_cloth_config_version = 19.0.147

# Fabric
fabric_loader_version = 0.17.2
fabric_api_version = 0.128.2+1.21.6

fabric_mod_menu_version = 15.0.2

# Forge
forge_version = 1.21.6-56.0.9
forge_loader_version = [56,)

# NeoForge
neoforge_version = 21.6.20-beta
neoforge_loader_version = [1,)