plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    shadowCommon

    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    //implementation "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"

    implementation("me.shedaniel.cloth:cloth-config-neoforge:${rootProject.common_cloth_config_version}")

    common(project(path: ':common')) { transitive = false }
    shadowCommon(project(path: ':common', configuration: "transformProductionNeoForge")) { transitive = false }
}

processResources {
    inputs.property 'neoforge_loader_version', rootProject.neoforge_loader_version
    inputs.property 'mod_license', rootProject.mod_license
    inputs.property 'mod_version', rootProject.mod_version
    inputs.property 'mod_name', rootProject.mod_name
    inputs.property 'mod_author', rootProject.mod_author
    inputs.property 'mod_desc', rootProject.mod_description
    inputs.property 'minecraft_version', rootProject.minecraft_version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand([
                'neoforge_loader_version': inputs.properties.neoforge_loader_version,
                'mod_license': inputs.properties.mod_license,
                'mod_version': inputs.properties.mod_version,
                'mod_name': inputs.properties.mod_name,
                'mod_author': inputs.properties.mod_author,
                'mod_desc': inputs.properties.mod_desc,
                'minecraft_version': inputs.properties.minecraft_version,
        ])
    }
}

jar {
    archiveClassifier = "raw"
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
}